export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT';
export const REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT';
export const UPDATE_CART_PRODUCT = 'UPDATE_CART_PRODUCT';
export const CHANGE_CART_PRODUCT = 'CHANGE_CART_PRODUCT';