export const CHANGE_CHECKOUT_BILLING_FORM_DATA = "CHANGE_CHECKOUT_BILLING_FORM_DATA";
export const CHANGE_CHECKOUT_BILLING_FORM_ERROR = "CHANGE_CHECKOUT_FORM_ERROR";

export const CHANGE_CHECKOUT_SHIPPING_FORM_DATA = "CHANGE_CHECKOUT_SHIPPING_FORM_DATA";
export const CHANGE_CHECKOUT_SHIPPING_FORM_ERROR = "CHANGE_CHECKOUT_SHIPPING_FORM_ERROR";
